### ISSUE TITLE
原有的 breadcrumbs links 被移除了

### ISSUE THREAD

**Issue by kiang** [kiang/elections#17]
在檢視候選人以及編輯候選人時，舊有頁面有著 breadcrumbs links ，新版畫面目前移除

![screenshot from 2015-10-18 01 58 03](https://cloud.githubusercontent.com/assets/47844/10560363/cb438b64-753b-11e5-9d03-7a2aee3d83d0.png)

有使用者表示少了這個導覽列操作上有點卡卡，沒辦法直接回到上一個畫面

**Comment by osk2** [comment]
原本覺得沒什麼必要，不過使用者習慣就加回來吧 :smirk:
