### ISSUE TITLE
檢視候選人的頁面少了針對狀態欄位的顏色變化

### ISSUE THREAD

**Issue by kiang** [kiang/elections#18]
候選人資料有個 stage 欄位，目前是

0 = 未登記
1 = 已登記
2 = 已當選

分別會對應到 css class

candidate-0
candidate-1
candidate-2

這個變化在檢視候選人的頁面目前被移除了，可以看看有沒有比較好的呈現方式

**Comment by osk2** [comment]
原本用色塊表示會讓人摸不著頭緒所以才先拿掉

目前想到的方式如下
* 替當選的候選人加了一個勳帶，如圖
* 未登記的候選人補上「未登記」的文字敘述
* 已登記的候選人按照原本標示編號沒變

![2015-10-18_165156](https://cloud.githubusercontent.com/assets/705280/10563321/9a99da36-75b8-11e5-9afd-6f86203b9e5a.png)

先解掉了，有問題再reopen吧 :)
