### ISSUE TITLE
Interview request

### ISSUE THREAD

**Issue by pigeon-lift** [kiang/elections#21]
Hi Kiang:

My name is Huizhong Wu and I'm a reporter with the AP in Taipei. I'm reaching out for a story I'm writing about Audrey Tang and wanted to reach out to you for a conversation. Can we connect over email? My email is hwu [at] ap.org

您好
我叫吳慧中是美聯社的記者。 我希望跟你聯繫因為我們要做一個關於唐鳳的專題。 方便的話可以email嗎？ 謝謝！

**Comment by kiang** [comment]
As mentioned in the email. I can't answer questions that I didn't get involved. You should ask her directly.
