### ISSUE TITLE
請求在行政區 API 當中取消相對應的選舉區所需要地圖位置的限制

### ISSUE THREAD

**Issue by allenlinli** [kiang/elections#22]
我希望從行政區 API 當中得到選舉區的列表（主要想要 2022）。
譬如呼叫新北市行政區 API，可以得到新北市長選舉區和新北市議員選舉區的列表。

謝謝你。

**Comment by kiang** [comment]
後來發現不是地圖的問題，是我程式判斷錯誤，已經調整 aa44df0125262597ebc0c39256d2dfd5a92852a2

現在你可以拿到整個行政區資料表的內容，只是得一層一層抓
https://elections.olc.tw/api/areas

**Comment by allenlinli** [comment]
太好了，現在行政區的 2022 年直轄市長、縣市長選舉區都可以顯示出來了
https://elections.olc.tw/api/areas/index/62053691-5c80-4c86-ad66-1619acb5b862

在那底下會跑出部分的直轄市議員、縣市議員，好像有點問題，我再另外開一個 issue。
